---
all:
  children:
    linux:
      hosts:
        srv-debian-01:
          ansible_host: 192.168.1.10
        srv-debian-02:
          ansible_host: 192.168.1.11
    windows:
      hosts:
        srv-win-01:
          ansible_host: 192.168.1.20
        srv-win-02:
          ansible_host: 192.168.1.21
